import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { useRouter } from "next/router";
import PageWrapper from "@/components/page-wrapper";
import HeaderMobile from "@/components/Header-Mobile";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Get Your Money Up Not Your Funny Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex">
              {/* <SideNav /> */}
              <main className="flex-1">
                {/* <MarginWidthWrapper> */}
                <Header />
                <HeaderMobile />
                <PageWrapper>{children}</PageWrapper>
                {/* </MarginWidthWrapper> */}
              </main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
