import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
// import ""
import Header from "@/components/Header";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import HeaderMobile from "@/components/Header-Mobile";
import SideNav from "@/components/Side-Nav";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Get Your Money Up Not Your Funny Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full">
      <HeaderMobile />
      <div className="flex h-full">
        <SideNav />
        <div className="w-full">{children}</div>
      </div>
    </div>
  );
}
